project:
  type: website
  output-dir: docs

website:
  title: "Prof.Tiago Pereira"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Ensino"
        href: ensino.qmd
      - text: "Contato"
        href: contato.qmd

lang: pt

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    
execute:
  freeze: true